library01/urls.py
from django.contrib import admin
from django.urls import path
from libmanage import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.homepage),
    path('signup/', views.user_signup,name='signup'),
    path('login/', views.user_login,name='login'),
    path('logout/', views.user_logout,name='logout'),
    path('dashboard/', views.dashboard,name='dashboard'),
    path('delete/<int:id>/',views.delete_data, name='deletedata'),
    path('<int:id>/',views.update_data, name='updatedata'),
]

libmanage/models.py
from django.db import models

# Create your models here.
class Student(models.Model):
    book=models.CharField(max_length=100)
    author=models.CharField(max_length=100)
    issuedto=models.CharField(max_length=80)
    issueddate=models.CharField(max_length=50)
    # returndate=models.CharField(max_length=50,Required=FALSE)

libmanage/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm,UsernameField
from django.contrib.auth.models import User
from.models import Student



class Signupform(UserCreationForm):
    password1=forms.CharField(label='Password',widget=forms.PasswordInput(attrs={'class':'form-control'}))
    password2=forms.CharField(label='Confirm Password(again)',widget=forms.PasswordInput(attrs={'class':'form-control'}))
    class Meta:
        model=User
        fields=['username','first_name','last_name','email']
        widgets={
        'username':forms.TextInput(attrs={'class':'form-control'}),
        'first_name':forms.TextInput(attrs={'class':'form-control'}),
        'last_name':forms.TextInput(attrs={'class':'form-control'}),
        'email':forms.EmailInput(attrs={'class':'form-control'}),
        }

class Loginform(AuthenticationForm):
    username=UsernameField(widget=forms.TextInput(attrs={'autofocus':True,'class':'form-control'}))
    password=forms.CharField(widget=forms.PasswordInput(attrs={'autocomplete':'current-password','class':'form-control'}))


class StudentRegistration(forms.ModelForm):
    class Meta:
        model=Student
        fields=['book','author','issuedto','issueddate']

libmanage/views.py
from django.shortcuts import render,HttpResponseRedirect
from.forms import Signupform,Loginform,StudentRegistration
from django.contrib import messages
from django.contrib.auth import authenticate,login,logout
from.models import Student
from django.contrib.auth.models import Group

def homepage(request):
    return render(request,'home.html')


# Signup
def user_signup(request):
    if request.method=='POST':
        form=Signupform(request.POST)
        if form.is_valid():
            messages.success(request,'You Are A Member Now....!')
            form.save()
            user=form.save()
            group=Group.objects.get(name='Student')
            user.groups.add(group)
    else:
        form=Signupform()
    return render(request,'signup.html',{'form':form})


# Login
def user_login(request):
    if not request.user.is_authenticated:
        if request.method=='POST':
            form=Loginform(request=request, data=request.POST)
            if form.is_valid():
                uname=form.cleaned_data['username']
                upass=form.cleaned_data['password']
                user=authenticate(username=uname,password=upass)
                if user is not None:
                    login(request,user)
                    return HttpResponseRedirect('/dashboard/')
        else:
            form=Loginform()
        return render(request,'login.html',{'form':form})
    else:
        return HttpResponseRedirect('/dashboard/')


# Dashboard
def dashboard(request):
    if request.user.is_authenticated:
        if request.method == "POST":
            fm=StudentRegistration(request.POST)
            if fm.is_valid():
                bk=fm.cleaned_data['book']
                au=fm.cleaned_data['author']
                it=fm.cleaned_data['issuedto']
                id=fm.cleaned_data['issueddate']
                reg=Student(book=bk,author=au,issuedto=it,issueddate=id)
                reg.save()
                fm=StudentRegistration()
        else:
            fm=StudentRegistration()
        stud=Student.objects.all()

        return render(request,"addshow.html",{'form':fm,'stu':stud})
    else:
        return HttpResponseRedirect('/login/')

# logout
def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/')


#this funcation udate/edit
def update_data(request,id):
    if request.method=='POST':
        pi=Student.objects.get(pk=id)
        fm=StudentRegistration(request.POST,instance=pi)
        if fm.is_valid():
            fm.save()
    else:
        pi=Student.objects.get(pk=id)
        fm=StudentRegistration(instance=pi)
    return render(request,'update.html',{'form':fm})


#this function will delete
def delete_data(request,id):
    if request.method=='POST':
        pi=Student.objects.get(pk=id)
        pi.delete()
        return HttpResponseRedirect('/dashboard/')

libmanage/templates/addshow.html
{% extends 'base.html' %}
{% block content %}

<div class="row">
  {% if perms.libmanage.delete_student %}
  <div class="col-sm-4">
    <h4 class="text-center alert alert-info">Add New </h4>
    <form action="" method="POST">
     {% csrf_token %}
     {{form.as_p}}

    <input type="submit" class="btn btn-warning mt-3 px-5 fw-bold" value="Add">

  </form>
</div>
  {% endif %}

<div class="col-sm-8">
    <h4 class="text-center alert alert-info">Show Data</h4>
{% if stu %}
<h4>Table Data</h4>
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Id</th>
        <th scope="col">Book</th>
        <th scope="col">Author</th>
        <th scope="col">Issued To</th>
        <th scope="col">Issued Date</th>
        {% if perms.libmanage.delete_student %}
        <th scope="col">Action</th>
        {% endif %}
      </tr>
    </thead>
    <tbody>
      {% for st in stu %}
      <tr>
        <th scope="row">{{st.id}}</th>
        <td>{{st.book}}</td>
        <td>{{st.author}}</td>
        <td>{{st.issuedto}}</td>
        <td>{{st.issueddate}}</td>
        {% if perms.libmanage.delete_student %}
        <td>
          <a href="{% url 'updatedata' st.id %}" class="btn btn-warning btn-sm">Edit</a>
          <form action="{% url 'deletedata' st.id %}" method="post" class="d-inline"> {% csrf_token %}
            <input type="submit" class="btn btn-danger" value="Delete">
          </form>
        </td>
        {% endif %}
      </tr>
  {%endfor%}
    </tbody>
  </table>




  
{%else%}
  <h4 class="text-center alert alert-warning">No Record</h4>
{% endif%}
</div>



</div>



{% endblock content %}

libmanage/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Library</title>
    <link rel="stylesheet" href="{% static 'enroll/css/bootstrap.css'%}">
</head>
<body>
    <div class="container-fluid bg-dark">
        {% include 'navbar.html' %}
    </div>
    
    <div class="container mt-5">
        <h2 class="text-center alert alert-danger">Library Mangment system</h2>
        {% block content %}  {% endblock content %}
    </div>


    <script src="{% static 'enroll/js/jquery.js'%}"></script>
    <script src="{% static 'enroll/js/propper.js'%}"></script>
    <script src="{% static 'enroll/js/bootstrap.js'%}"></script>
</body>
</html>

libmanage/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    {% if request.user.is_authenticated %}

    
    {% else %}
    <div class="col-sm-10 offset-1">
        <h3 class="text-white my-5">Home Page</h3>
        <div class="container mt-5">
            <h2 class="text-center alert alert-info"> Login or Signup to proceed</h2>
            
        </div>
    </div>
    {% endif %}

{% endblock content %}

libmanage/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <div class="col-sm-10 offset-1">
        <h3 class="text-white my-5">Login Page</h3>
        <form action="" method="post" novalidate>
            {% csrf_token %}
            {% for fm in form %}
              <div>
                {{fm.label_tag}} {{fm}}
                <small class="text-warning">{{fm.errors|striptags}}</small>
              </div>
            {% endfor %} <br />
            <input type="submit" class="btn btn-primary" value="Login" />
            {% if form.non_field_errors %} {% for error in form.non_field_errors %}
            <p class="alert alert-danger my-3">{{error}}</p>
            {% endfor %} {% endif %}
          </form>
    </div>

{% endblock content %}

libmanage/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      {% if request.user.is_authenticated %}
      <a class="navbar-brand" href="{% url 'dashboard' %}">Library</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>      
      {% else %}
      <a class="navbar-brand" href="/">Library</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      {% endif %}
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'dashboard' %}">Dashboard</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'signup' %}">Signup</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Login</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

libmanage/templates/signup.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <div class="col-sm-10 offset-1">
        <h3 class="text-white my-5">Signup here</h3>
        {% if messages %}
            {% for message in messages %}
                <p {% if message.tags %} class="alert alert-{{message.tags}} mb-5" {% endif %}>{{message}}</p>
            {% endfor %}
        {% endif %}
        <form action="" method="post" novalidate>
            {% csrf_token %}
            {% for fm in form %}
                <div class="form-group">
                    {{fm.label_tag}} {{fm}} <small class="text-warning">{{fm.errors|striptags}}</small>
                </div>
            {% endfor %} <br>
            <input type="submit" value="submit" class="btn btn-primary">
            {% if form.non_field_errors %}
                {% for error in form.non_fiels_errors %}
                    <p class="alert alert-danger my-3">{{error}}</p>
                {% endfor %}
            {% endif %}
        </form>
    </div>

{% endblock content %}

libmanage/templates/update.html
{% extends 'base.html'%}
{% block content %}

<div class="row">
    <div class="col-sm-8 offet-2">
        <h4 class="alert alert-info">Update</h4>
        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" class="btn btn-success" value="Update">
            <a href="{% url 'dashboard' %}" class="btn btn-info">Back To Dashboard</a>
        </form>
    </div>
</div>


{% endblock content %}